eCommerceProject/Areas/Admin/Controllers/AdminCustomersController.cs
using ClosedXML.Excel;
using eCommerceProject.Models;
using PagedList;
using System;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace eCommerceProject.Areas.Admin.Controllers
{
	[Authorize(Roles = "Admin,Seller")]
	public class AdminCustomersController : Controller
	{
		private ApplicationDbContext db = new ApplicationDbContext();

		// GET: AdminCustomers

		public ActionResult Index(int? page, string search, int? filter)
		{
			//view all itemn in page
			var totalItem = db.Customers.ToList().Count();
			ViewBag.totalItem = totalItem;
			// get seller db
			var customers = from s in db.Customers.AsNoTracking().OrderBy(t => t.CreatedDate).ToList()
											select s;

			if (!String.IsNullOrWhiteSpace(search))
			{
				customers = db.Customers.Where(s => s.FullName.Contains(search)
															 || s.PhoneNumber.Contains(search)).ToList();
			}

			if (!String.IsNullOrWhiteSpace(filter.ToString()))
			{
				//Filter results based on company selected.

				customers = customers.Where(x => x.StatusID.Equals(filter)).ToList();


			}

			return View(customers.ToPagedList(page ?? 1, 2));
		}

		// GET: AdminCustomers/Details/5
		public ActionResult Details(string id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Customer user = db.Customers.Find(id);
			if (user == null)
			{
				return HttpNotFound();
			}
			return View(user);
		}

		// GET: AdminCustomers/Create


		// GET: AdminCustomers/Edit/5
		public ActionResult Edit(string id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Customer customer = db.Customers.Find(id);

			if (customer == null)
			{
				return HttpNotFound();
			}

			var customers = new Customer()
			{
				Id = customer.Id,
				StatusID = customer.StatusID,
				FullName = customer.FullName,
				Address = customer.Address,
				Email = customer.Email,
				PhoneNumber = customer.PhoneNumber
			};
			return View(customers);
		}

		// POST: AdminCustomers/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to, for 
		// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit([Bind(Include = "Id,FullName,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName,Address,StatusID")] Customer user)
		{
			if (ModelState.IsValid)
			{
				var post = db.Customers.FirstOrDefault(t => t.Id == user.Id);
				post.StatusID = user.StatusID;
				post.FullName = user.FullName;
				post.Address = user.Address;
				post.PhoneNumber = user.PhoneNumber;
				post.Email = user.Email;
				db.Entry(post).State = EntityState.Modified;
				db.SaveChanges();
				TempData["success"] = "Edit Success!";
				return RedirectToAction("Index");
			}
			return View(user);
		}

		// GET: AdminCustomers/Delete/5
		public ActionResult Delete(string id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Customer user = db.Customers.Find(id);
			if (user == null)
			{
				return HttpNotFound();
			}
			return View(user);
		}

		// POST: AdminCustomers/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public ActionResult DeleteConfirmed(string id)
		{
			Customer user = db.Customers.Find(id);
			db.Users.Remove(user);
			db.SaveChanges();
			TempData["success"] = "Delete Success!";
			return RedirectToAction("Index");
		}

		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				db.Dispose();
			}
			base.Dispose(disposing);
		}
		//export excel
		[HttpPost]
		public FileResult Export()
		{

			DataTable dt = new DataTable("ListCustomerInSystem");
			dt.Columns.AddRange(new DataColumn[4] { new DataColumn("Id"),
																						new DataColumn("FullName"),
																						new DataColumn("Email"),
																						new DataColumn("PhoneNumber")});

			var customers = from customer in db.Customers.Take(10)
											select customer;

			foreach (var customer in customers)
			{
				dt.Rows.Add(customer.Id, customer.FullName, customer.Email, customer.PhoneNumber);
			}

			using (XLWorkbook wb = new XLWorkbook())
			{
				wb.Worksheets.Add(dt);
				using (MemoryStream stream = new MemoryStream())
				{
					wb.SaveAs(stream);
					return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "ListCustomerInSystem.xlsx");
				}
			}
		}
	}
}

eCommerceProject/Areas/Admin/Views/AdminCustomers/Delete.cshtml
@model eCommerceProject.Models.Customer

@{
	ViewBag.Title = "Delete";
	Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Customer <strong class="btn-tone"> @Model.FullName</strong></h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger btn-tone m-r-5" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

eCommerceProject/Areas/Admin/Views/AdminCustomers/Details.cshtml
@model eCommerceProject.Models.Customer

@{
	ViewBag.Title = "Details";
	Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailConfirmed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailConfirmed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PasswordHash)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PasswordHash)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecurityStamp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecurityStamp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumberConfirmed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumberConfirmed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TwoFactorEnabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TwoFactorEnabled)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LockoutEndDateUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LockoutEndDateUtc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LockoutEnabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LockoutEnabled)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccessFailedCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccessFailedCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

eCommerceProject/Areas/Admin/Views/AdminCustomers/Edit.cshtml
@model eCommerceProject.Models.Customer
@using eCommerceProject.Enums;
@{
	ViewBag.Title = "Edit";
	Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Customer</h2>

@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		<h4>User</h4>
		<hr />
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		@Html.HiddenFor(model => model.Id)

		<div class="form-group">
			@Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
			</div>
		</div>



		<div class="form-group">
			@Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
			</div>
		</div>



		<div class="form-group">
			@Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">
			@Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">

				@Html.DropDownListFor(model => model.StatusID,
					EnumHelper.GetSelectList(typeof(AccountStatus)),
					"Select Status",
					new { @class = "form-control" })
			</div>
		</div>

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Save" class="btn btn-success btn-tone m-r-5" />
			</div>
		</div>
	</div>
}

<div>
	@Html.ActionLink("Back to List", "Index")
</div>

eCommerceProject/Areas/Admin/Views/AdminCustomers/Index.cshtml
@model PagedList.IPagedList<eCommerceProject.Models.Customer>
@using PagedList.Mvc;


@{
	//int CurrentPage = ViewBag.CurrentPage;
	ViewBag.Title = "Index";
	Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<style>
	.active {
		color: #02a499;
	}

	.unactive {
		color: #ec4561;
	}

	.disabled {
		color: #f8b425;
	}


	.ul.pagination {
		display: inline-block;
		padding: 0;
		margin: 0;
	}

	ul.pagination li {
		display: inline;
		/*border: 1px solid #02a499;*/
		border-radius: 50% !important;
		margin: 0 5px;
	}

		ul.pagination li a {
			color: black;
			float: left;
			padding: 8px 16px;
			text-decoration: none;
			border-radius: 50% !important;
			transition: background-color .3s;
		}

		ul.pagination li.active {
			background-color: #02a499;
			color: white;
			border-radius: 50% !important;
			margin: 0 5px;
		}

		ul.pagination li a.active {
			background-color: #02a499;
			color: white;
			border-radius: 50% !important;
			margin: 0 5px;
		}

		ul.pagination li a:hover:not(.active) {
			background-color: #02a499;
			color: white;
			border-radius: 50% !important;
		}
</style>


<div class="page-header">
	<h2 class="header-title">Customers List</h2>
	<div class="header-sub-title">
		<nav class="breadcrumb breadcrumb-dash">
			<a href="#" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
			<a class="breadcrumb-item" href="#">Users</a>
			<span class="breadcrumb-item active">Customers List : @ViewBag.CurrentPage</span>
		</nav>
	</div>
</div>
<div class="card">
	<div class="card-body">
		<div class="row m-b-30">
			<div class="col-lg-8">
				<form>
					@using (Html.BeginForm("Index", "AdminCustomers", "POST"))
					{
						<div class="d-md-flex ">
							<div class="m-b-10 col-md-3 form-row ">



								@Html.DropDownList("filter", new List<SelectListItem>{ new SelectListItem {Text = "Actived", Value = "1" + ""},
														 new SelectListItem {Text = "Unactived", Value = "2"},
														 new SelectListItem {Text = "Disabled", Value = "3"},
													 }, "--Select Status--", new { @class = "form-control col-md-12 " })


							</div>
							<div class="input-affix m-b-10 ">

								<i class="prefix-icon anticon anticon-search"></i>
								@Html.TextBox("search", null, new { @type = "text", @class = "form-control col-md-10", @placeholder = "Search..." })


							</div>
							<input style="height: 45px" value="Filter" type="submit" class="btn btn-info btn-tone m-r-5" />

						</div>
					}
				</form>
			</div>
			<div class="col-lg-4 text-right">
				@using (Html.BeginForm("Export", "AdminCustomers", new { @class = "form-control" }, FormMethod.Post))
				{
					<button class="btn btn-primary btn-tone m-r-5">
						<i class="anticon anticon-plus"></i>
						@Html.ActionLink("Create New", "CreateAccount", "AdminAccount" , new { area = "Admin" }, new { })
					</button>

					<button class="btn btn-primary">

						<i class="anticon anticon-file-excel "></i>
						<span type="submit">
							Export
						</span>

					</button>

				}
			</div>

		</div>
		<div class="table-responsive">
			<table class="table table-hover e-commerce-table">
				<thead>
					<tr>

						<th>Full Name</th>
						<th>Email</th>
						<th>Phone Number</th>
						<th>Address</th>
						<th>Status</th>
						<th>#</th>
					</tr>
				</thead>
				<tbody>

					@if (Model != null && Model.Count > 0)
					{
						foreach (var item in Model)
						{


							<tr>
								<td>
									@Html.DisplayFor(modelItem => item.FullName)
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.Email)
								</td>


								<td>
									@Html.DisplayFor(modelItem => item.PhoneNumber)
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.Address)
								</td>
								<td>
									@if (item.StatusID == 1)
									{
										<a><span class="active">●</span> Actived</a>

									}
									@if (item.StatusID == 2)
									{
										<a><span class="unactive">●</span> Unactive</a>

									}
									@if (item.StatusID == 3)
									{
										<a><span class="disabled">●</span> Disabled</a>

									}
								</td>

								<td>
									@Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-success btn-tone m-r-5" })
									@Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-info btn-tone m-r-5" })
									@Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger btn-tone m-r-5" })
								</td>
							</tr>
						}
					}
					else
					{
						<a style="color:red">No User In Here!</a>
					}


				</tbody>
			</table>
			<div class="container">
				<div class="row">
					<div class="col">
						Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
						to @Model.PageCount of @ViewBag.totalItem items
					</div>
					

							@Html.PagedListPager(Model, page => Url.Action("Index", new { page = page, search = Request.QueryString["search"], filter = Request.QueryString["filter"] }), new PagedListRenderOptions { LinkToFirstPageFormat = "<< First", LinkToPreviousPageFormat = "< Previous", LinkToNextPageFormat = "Next >", LinkToLastPageFormat = "Last >>" })
						
				</div>
			</div>

		</div>
	</div>
</div>