eCommerceProject/Areas/Admin/Controllers/SendEmailsController.cs
using eCommerceProject.Models;
using System;
using System.Configuration;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web.Mvc;

namespace eCommerceProject.Areas.Admin.Controllers
{
	[Authorize(Roles = "Admin,Seller")]
	public class SendEmailsController : Controller
	{
		private ApplicationDbContext db = new ApplicationDbContext();

		// GET: Admin/SendEmails
		public ActionResult Index()
		{
			return View(db.SendEmails.ToList());
		}

		// GET: Admin/SendEmails/Details/5
		public ActionResult Details(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			SendEmail sendEmail = db.SendEmails.Find(id);
			if (sendEmail == null)
			{
				return HttpNotFound();
			}
			return View(sendEmail);
		}

		// GET: Admin/SendEmails/Create
		public ActionResult Create()
		{
			return View();
		}

		// POST: Admin/SendEmails/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to, for 
		// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateInput(false)]
		public ActionResult Create(SendEmail sendEmail)
		{
			//string path = "~/Content/ImageEmail/" + Guid.NewGuid() + "/";
			if (ModelState.IsValid)
			{

				MailMessage mailMessage = new MailMessage();
				mailMessage.From = new MailAddress(ConfigurationManager.AppSettings["Email"].ToString());
				var ToMuliId = sendEmail.CustomerEmail.Split(',', ';');
				foreach (var ToEMailId in ToMuliId)
				{
					mailMessage.To.Add(new MailAddress(ToEMailId)); //adding multiple TO Email Id  
				}

				//mailMessage.CC.Add(new MailAddress("solutions@yogihosting.com"));

				string body = string.Empty;
				using (StreamReader reader = new StreamReader(Server.MapPath("~/Content/Template.html")))
				{
					body = reader.ReadToEnd();
				}
				mailMessage.Body = body.Replace("{Description}", sendEmail.body);
				mailMessage.Subject = sendEmail.subject;

				mailMessage.IsBodyHtml = true;

				//if (sendEmail.file[0] != null)
				//{
				//	Directory.CreateDirectory(Server.MapPath(path));
				//	foreach (HttpPostedFileBase file in sendEmail.file)
				//	{
				//		string filePath = Server.MapPath(path + file.FileName);
				//		file.SaveAs(filePath);

				//		mailMessage.Attachments.Add(new Attachment(Server.MapPath(path + file.FileName)));
				//	}
				//}

				SmtpClient smtpClient = new SmtpClient("smtp.gmail.com", Convert.ToInt32(587));
				System.Net.NetworkCredential credentials = new System.Net.NetworkCredential(ConfigurationManager.AppSettings["Email"].ToString(), ConfigurationManager.AppSettings["Password"].ToString());
				smtpClient.Credentials = credentials;
				smtpClient.EnableSsl = true;
				//save db
				var newMail = new SendEmail()
				{
					CustomerEmail = sendEmail.CustomerEmail,
					subject = sendEmail.subject,
					body = sendEmail.body,

				};

				db.SendEmails.Add(newMail);
				db.SaveChanges();
				ViewBag.Result = "Mail Sent!";

				//send mail
				//await UserManager.SendEmailAsync(allUserCustomer., "New From COCO Store", "Some thing news.... <br> out now \"" + newBlog.Title + "\"  was submited. Thanks for your submited Ideas, pls wait for QA respond!");

				try
				{
					smtpClient.Send(mailMessage);
					TempData["success"] = "Send Success!";
				}
				catch (Exception ex)
				{
					ViewBag.Result = ex.Message;
					TempData["danger"] = "Send Failed!";
				}
			}

			return RedirectToAction("Index");
		}

		// GET: Admin/SendEmails/Edit/5
		public ActionResult Edit(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			SendEmail sendEmail = db.SendEmails.Find(id);
			if (sendEmail == null)
			{
				return HttpNotFound();
			}
			return View(sendEmail);
		}

		// POST: Admin/SendEmails/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to, for 
		// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit([Bind(Include = "Id,CustomerID,subject,body")] SendEmail sendEmail)
		{
			if (ModelState.IsValid)
			{
				db.Entry(sendEmail).State = EntityState.Modified;
				db.SaveChanges();
				return RedirectToAction("Index");
			}
			return View(sendEmail);
		}

		// GET: Admin/SendEmails/Delete/5
		public ActionResult Delete(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			SendEmail sendEmail = db.SendEmails.Find(id);
			if (sendEmail == null)
			{
				return HttpNotFound();
			}
			return View(sendEmail);
		}

		// POST: Admin/SendEmails/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public ActionResult DeleteConfirmed(int id)
		{
			SendEmail sendEmail = db.SendEmails.Find(id);
			db.SendEmails.Remove(sendEmail);
			db.SaveChanges();
			return RedirectToAction("Index");
		}

		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				db.Dispose();
			}
			base.Dispose(disposing);
		}
	}
}

eCommerceProject/Areas/Admin/Views/SendEmails/Create.cshtml
@model eCommerceProject.Models.SendEmail

@{
	ViewBag.Title = "Create";
	Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<script src="//cdn.ckeditor.com/4.15.0/full/ckeditor.js"></script>
<style>
	.emailDiv label {
		display: block;
		margin: 0;
		text-transform: capitalize;
	}

	table tr td > span {
		display: block;
		color: burlywood;
	}

	.emailDiv > form > div > div {
		padding-top: 25px;
	}

	table {
		width: 100%;
	}
</style>
<div class="page-header">
	<h2 class="header-title">@ViewBag.Title</h2>
	<div class="header-sub-title">
		<nav class="breadcrumb breadcrumb-dash">
			<a href="#" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
			<a class="breadcrumb-item" href="#">Send Mail</a>
			<span class="breadcrumb-item active">@ViewBag.Title</span>
		</nav>
	</div>
	
</div>

<h3>@ViewBag.Result</h3>
@using (Html.BeginForm("Create", "SendEmails", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
	@Html.AntiForgeryToken()
	<form>
		

				<div class="form-group">
					@Html.Label("To User : ", new { htmlAttributes = new { @class = "control-label col-md-2" } })
					@Html.TextAreaFor(model => model.CustomerEmail, 5, 100, new { @class = "form-control col-md-10" })
					@Html.ValidationMessageFor(model => model.CustomerEmail)
				</div>

				<div class="form-group">
					@Html.Label("Subject : ", new { htmlAttributes = new { @class = "control-label col-md-2" } })
					@Html.EditorFor(model => model.subject, new { htmlAttributes = new { @class = "form-control col-md-10" } })
					@Html.ValidationMessageFor(model => model.subject)
				</div>
			
		
				<div class="form-group">
					@Html.Label("Content: ", new { htmlAttributes = new { @class = "control-label col-md-2" } })
					@Html.TextAreaFor(model => model.body)
					<script type="text/javascript" language="javascript">
										CKEDITOR.replace(@Html.IdFor(model => model.body));
					</script>
					@Html.ValidationMessageFor(model => model.body)
					</div>
			<input type="submit" value="Send" class="btn btn-success btn-tone col-md-12" />
	</form>
}

<div>
	@Html.ActionLink("Back to List", "Index")
</div>
@section scripts{
	<script src="//cdn.ckeditor.com/4.19.1/full/ckeditor.js"></script>
}
@Scripts.Render("~/jQuery")
@Scripts.Render("~/jQueryValidate")
@Scripts.Render("~/Unobtrusive")
<script>
	$(document).ready(function () {
		$("#submitButton").click(function () {
			CKEDITOR.instances["description"].updateElement();
			$("#description").show();
		});
	});
	
		function getUrlParam(paramName) {
					var reParam = new RegExp('(?:[\?&]|&amp;)' + paramName + '=([^&]+)', 'i') ;
		var match = window.location.search.match(reParam) ;

					return (match && match.length > 1) ? match[1] : '' ;
			}

		$(function(){

			var funcNum = getUrlParam('CKEditorFuncNum');

		var elf = $('#elfinder').elfinder({
			url : 'admin.php?mod=system&op=getFileManagerConnector',
		getFileCallback : function(fileUrl) {
			window.opener.CKEDITOR.tools.callFunction(funcNum, fileUrl, function () {

				var widthField, heightField, urlField,
					dialog = this.getDialog(),
					width  = '560px';

				if (dialog.getName() == 'image') {
					widthField = dialog.getContentElement('info', 'txtWidth');
					
					urlField = dialog.getContentElement('info', 'txtUrl');

					if (urlField)
						urlField.setValue(fileUrl);

					if (widthField)
						widthField.setValue(width);

					if (heightField)
						heightField.setValue(height);
				}

				return false;

			});
		window.close();

							},
			}).elfinder('instance');
		});
</script>

eCommerceProject/Areas/Admin/Views/SendEmails/Delete.cshtml
@model eCommerceProject.Models.SendEmail

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
	<h2 class="header-title">@ViewBag.Title</h2>
	<div class="header-sub-title">
		<nav class="breadcrumb breadcrumb-dash">
			<a href="#" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
			<a class="breadcrumb-item" href="#">Send Mail</a>
			<span class="breadcrumb-item active">@ViewBag.Title</span>
		</nav>
	</div>

</div>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SendEmail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Customer Email:")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerEmail)
        </dd>

        <dt>
            @Html.DisplayName("Subject: ")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.subject)
        </dd>

        <dt>
            @Html.DisplayName("Body: ")
        </dt>

        <dd>
            @Html.Raw(Model.body)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" onclick="return confirm('Are you sure?')" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

eCommerceProject/Areas/Admin/Views/SendEmails/Details.cshtml
@model eCommerceProject.Models.SendEmail

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
	<h2 class="header-title">@ViewBag.Title</h2>
	<div class="header-sub-title">
		<nav class="breadcrumb breadcrumb-dash">
			<a href="#" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
			<a class="breadcrumb-item" href="#">Send Mail</a>
			<span class="breadcrumb-item active">@ViewBag.Title</span>
		</nav>
	</div>

</div>

<div>
    <h4>SendEmail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CustomerEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.subject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.subject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.body)
        </dt>

        <dd>
            @Html.Raw(Model.body)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

eCommerceProject/Areas/Admin/Views/SendEmails/Edit.cshtml
@model eCommerceProject.Models.SendEmail

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SendEmail</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.subject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.subject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.subject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

eCommerceProject/Areas/Admin/Views/SendEmails/Index.cshtml
@model IEnumerable<eCommerceProject.Models.SendEmail>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Index</h2>


	<div class="col-lg-4 text-right">
		<button class="btn btn-primary btn-tone">
			<i class="anticon anticon-plus-circle m-r-5"></i>
			<span>@Html.ActionLink("Add New", "Create")</span>
		</button>
	</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CustomerEmail)
        </th>
       
        <th>
            @Html.DisplayNameFor(model => model.body)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CustomerEmail)
        </td>
        
				<td>
					@Html.DisplayFor(modelItem =>item.subject)
				</td>
        <td>
           
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>